CREATE TABLE LOGS (ID INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1  NOT NULL GENERATED ALWAYS AS IDENTITY, OWNER INTEGER, "ACTION" VARCHAR(255), DURATION VARCHAR(255), DATETIME TIMESTAMP, PRIMARY KEY (ID));

CREATE TABLE METEO_PORTFOLIO (ID INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1  NOT NULL GENERATED ALWAYS AS IDENTITY, "NAME" VARCHAR(255), OWNER INTEGER, PRIMARY KEY (ID));

CREATE TABLE PORTFOLIO_ADDRESSES (ID INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1  NOT NULL GENERATED ALWAYS AS IDENTITY, ADDRESS VARCHAR(255), PORTFOLIO INTEGER, PRIMARY KEY (ID));

CREATE TABLE USERS (ID INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1  NOT NULL GENERATED ALWAYS AS IDENTITY, FIRSTNAME VARCHAR(255), LASTNAME VARCHAR(255), USERNAME VARCHAR(255), PASSWORD VARCHAR(255), PRIMARY KEY (ID));


INSERT INTO NWTIS.LOGS (OWNER, "ACTION", DURATION, DATETIME) 
	VALUES (NULL, 'Neprijavljeni korisnik pristupa: [/kdomic_aplikacija_2_web/portfelj/dodajPortfelj.xhtml]', NULL, '2014-06-05 21:04:57.028');
INSERT INTO NWTIS.LOGS (OWNER, "ACTION", DURATION, DATETIME) 
	VALUES (NULL, 'Neprijavljeni korisnik pristupa: [/kdomic_aplikacija_2_web/portfelj/prijava.xhtml]', NULL, '2014-06-05 21:04:58.156');
INSERT INTO NWTIS.LOGS (OWNER, "ACTION", DURATION, DATETIME) 
	VALUES (NULL, 'Neprijavljeni korisnik pristupa: [/kdomic_aplikacija_2_web/portfelj/prijava.xhtml]', NULL, '2014-06-05 21:08:43.401');
INSERT INTO NWTIS.LOGS (OWNER, "ACTION", DURATION, DATETIME) 
	VALUES (NULL, 'Neprijavljeni korisnik pristupa: [/kdomic_aplikacija_2_web/portfelj/prijava.xhtml]', NULL, '2014-06-05 21:09:03.354');
INSERT INTO NWTIS.LOGS (OWNER, "ACTION", DURATION, DATETIME) 
	VALUES (NULL, 'Neprijavljeni korisnik pristupa: [/kdomic_aplikacija_2_web/portfelj/prijava.xhtml]', NULL, '2014-06-05 21:09:06.137');
INSERT INTO NWTIS.LOGS (OWNER, "ACTION", DURATION, DATETIME) 
	VALUES (1, 'Pristup stranici: [/kdomic_aplikacija_2_web/portfelj/dodajPortfelj.xhtml]', NULL, '2014-06-05 21:09:22.85');
INSERT INTO NWTIS.LOGS (OWNER, "ACTION", DURATION, DATETIME) 
	VALUES (1, 'Pristup stranici: [/kdomic_aplikacija_2_web/portfelj/index.xhtml]', NULL, '2014-06-05 21:09:40.135');
INSERT INTO NWTIS.LOGS (OWNER, "ACTION", DURATION, DATETIME) 
	VALUES (1, 'Odjava korisnika: [kdomic]', NULL, '2014-06-05 21:09:42.551');
INSERT INTO NWTIS.LOGS (OWNER, "ACTION", DURATION, DATETIME) 
	VALUES (NULL, 'Neprijavljeni korisnik pristupa: [/kdomic_aplikacija_2_web/portfelj/prijava.xhtml]', NULL, '2014-06-05 21:09:42.635');
INSERT INTO NWTIS.LOGS (OWNER, "ACTION", DURATION, DATETIME) 
	VALUES (NULL, 'Ilegalni pristup neprijavljenog korisnika: [/kdomic_aplikacija_2_web/portfelj/dodajPortfelj.xhtml]', NULL, '2014-06-05 21:09:45.379');
INSERT INTO NWTIS.LOGS (OWNER, "ACTION", DURATION, DATETIME) 
	VALUES (NULL, 'Neprijavljeni korisnik pristupa: [/kdomic_aplikacija_2_web/portfelj/prijava.xhtml]', NULL, '2014-06-05 21:09:45.457');
INSERT INTO NWTIS.LOGS (OWNER, "ACTION", DURATION, DATETIME) 
	VALUES (NULL, 'Neprijavljeni korisnik pristupa: [/kdomic_aplikacija_2_web/portfelj/prijava.xhtml]', NULL, '2014-06-06 00:40:55.491');
INSERT INTO NWTIS.LOGS (OWNER, "ACTION", DURATION, DATETIME) 
	VALUES (NULL, 'Neprijavljeni korisnik pristupa: [/kdomic_aplikacija_2_web/portfelj/registracija.xhtml]', NULL, '2014-06-06 00:41:00.291');
INSERT INTO NWTIS.LOGS (OWNER, "ACTION", DURATION, DATETIME) 
	VALUES (NULL, 'Neprijavljeni korisnik pristupa: [/kdomic_aplikacija_2_web/portfelj/registracija.xhtml]', NULL, '2014-06-06 00:41:14.099');
INSERT INTO NWTIS.LOGS (OWNER, "ACTION", DURATION, DATETIME) 
	VALUES (NULL, 'Neprijavljeni korisnik pristupa: [/kdomic_aplikacija_2_web/portfelj/prijava.xhtml]', NULL, '2014-06-06 00:41:22.998');
INSERT INTO NWTIS.LOGS (OWNER, "ACTION", DURATION, DATETIME) 
	VALUES (NULL, 'Neprijavljeni korisnik pristupa: [/kdomic_aplikacija_2_web/portfelj/prijava.xhtml]', NULL, '2014-06-06 00:41:27.396');
INSERT INTO NWTIS.LOGS (OWNER, "ACTION", DURATION, DATETIME) 
	VALUES (3, 'Odjava korisnika: [admin]', NULL, '2014-06-06 00:41:34.104');
INSERT INTO NWTIS.LOGS (OWNER, "ACTION", DURATION, DATETIME) 
	VALUES (NULL, 'Neprijavljeni korisnik pristupa: [/kdomic_aplikacija_2_web/portfelj/prijava.xhtml]', NULL, '2014-06-06 00:41:34.151');
INSERT INTO NWTIS.LOGS (OWNER, "ACTION", DURATION, DATETIME) 
	VALUES (NULL, 'Ilegalni pristup ADMIN DIJELU neprijavljenog korisnika: [/kdomic_aplikacija_2_web/admin/emailPostavke.xhtml]', NULL, '2014-06-06 00:47:12.898');
INSERT INTO NWTIS.LOGS (OWNER, "ACTION", DURATION, DATETIME) 
	VALUES (NULL, 'Neprijavljeni korisnik pristupa: [/kdomic_aplikacija_2_web/portfelj/prijava.xhtml]', NULL, '2014-06-06 00:47:12.971');

	
	INSERT INTO NWTIS.METEO_PORTFOLIO ("NAME", OWNER) 
	VALUES ('Test 1', 1);
INSERT INTO NWTIS.METEO_PORTFOLIO ("NAME", OWNER) 
	VALUES ('Test 2', 1);
INSERT INTO NWTIS.METEO_PORTFOLIO ("NAME", OWNER) 
	VALUES ('Hrvatska', 1);
INSERT INTO NWTIS.METEO_PORTFOLIO ("NAME", OWNER) 
	VALUES ('Istra', 1);
INSERT INTO NWTIS.METEO_PORTFOLIO ("NAME", OWNER) 
	VALUES ('Dalmacija', 1);
INSERT INTO NWTIS.METEO_PORTFOLIO ("NAME", OWNER) 
	VALUES ('Strane semlje', 1);
INSERT INTO NWTIS.METEO_PORTFOLIO ("NAME", OWNER) 
	VALUES ('Strani', 1);
INSERT INTO NWTIS.METEO_PORTFOLIO ("NAME", OWNER) 
	VALUES ('Strane', 1);
INSERT INTO NWTIS.METEO_PORTFOLIO ("NAME", OWNER) 
	VALUES ('rew', 1);
INSERT INTO NWTIS.METEO_PORTFOLIO ("NAME", OWNER) 
	VALUES ('132', 1);
INSERT INTO NWTIS.METEO_PORTFOLIO ("NAME", OWNER) 
	VALUES ('Test 3', 1);
INSERT INTO NWTIS.METEO_PORTFOLIO ("NAME", OWNER) 
	VALUES ('fds', 1);
INSERT INTO NWTIS.METEO_PORTFOLIO ("NAME", OWNER) 
	VALUES ('dsad', 1);
INSERT INTO NWTIS.METEO_PORTFOLIO ("NAME", OWNER) 
	VALUES ('dsa', 1);
INSERT INTO NWTIS.METEO_PORTFOLIO ("NAME", OWNER) 
	VALUES ('ze', 1);
INSERT INTO NWTIS.METEO_PORTFOLIO ("NAME", OWNER) 
	VALUES ('fdsa', 1);
INSERT INTO NWTIS.METEO_PORTFOLIO ("NAME", OWNER) 
	VALUES ('dfsa', 1);
INSERT INTO NWTIS.METEO_PORTFOLIO ("NAME", OWNER) 
	VALUES ('Test nešto', 1);
INSERT INTO NWTIS.METEO_PORTFOLIO ("NAME", OWNER) 
	VALUES ('Test 5', 1);
INSERT INTO NWTIS.METEO_PORTFOLIO ("NAME", OWNER) 
	VALUES ('Nove adrese', 1);

INSERT INTO NWTIS.PORTFOLIO_ADDRESSES (ADDRESS, PORTFOLIO) 
	VALUES ('Varazdin, Pavlinska 2', 1);
INSERT INTO NWTIS.PORTFOLIO_ADDRESSES (ADDRESS, PORTFOLIO) 
	VALUES ('Zagreb, Trg bana Josipa Jelačića', 2);
INSERT INTO NWTIS.PORTFOLIO_ADDRESSES (ADDRESS, PORTFOLIO) 
	VALUES ('Čakovec, Ulica kralja Tomislava 1', 2);
INSERT INTO NWTIS.PORTFOLIO_ADDRESSES (ADDRESS, PORTFOLIO) 
	VALUES ('Varazdin, Pavlinska 2', 3);
INSERT INTO NWTIS.PORTFOLIO_ADDRESSES (ADDRESS, PORTFOLIO) 
	VALUES ('Čakovec, Ulica kralja Tomislava 1', 3);
INSERT INTO NWTIS.PORTFOLIO_ADDRESSES (ADDRESS, PORTFOLIO) 
	VALUES ('Zagreb, Trg bana Josipa Jelačića', 3);
INSERT INTO NWTIS.PORTFOLIO_ADDRESSES (ADDRESS, PORTFOLIO) 
	VALUES ('Rijeka, Trg republike', 3);
INSERT INTO NWTIS.PORTFOLIO_ADDRESSES (ADDRESS, PORTFOLIO) 
	VALUES ('Split, Obala Hrvatskog narodnog preporoda', 3);
INSERT INTO NWTIS.PORTFOLIO_ADDRESSES (ADDRESS, PORTFOLIO) 
	VALUES ('Tar, Croatia', 4);
INSERT INTO NWTIS.PORTFOLIO_ADDRESSES (ADDRESS, PORTFOLIO) 
	VALUES ('Novigrad, Croatia', 4);
INSERT INTO NWTIS.PORTFOLIO_ADDRESSES (ADDRESS, PORTFOLIO) 
	VALUES ('Pula, Croatia', 4);
INSERT INTO NWTIS.PORTFOLIO_ADDRESSES (ADDRESS, PORTFOLIO) 
	VALUES ('52000, Pazin, Croatia', 4);
INSERT INTO NWTIS.PORTFOLIO_ADDRESSES (ADDRESS, PORTFOLIO) 
	VALUES ('Šibenik, Croatia', 5);
INSERT INTO NWTIS.PORTFOLIO_ADDRESSES (ADDRESS, PORTFOLIO) 
	VALUES ('Graz, Opernring 14', 6);
INSERT INTO NWTIS.PORTFOLIO_ADDRESSES (ADDRESS, PORTFOLIO) 
	VALUES ('Graz, Opernring 14', 7);
INSERT INTO NWTIS.PORTFOLIO_ADDRESSES (ADDRESS, PORTFOLIO) 
	VALUES ('Graz, Opernring 14', 8);
INSERT INTO NWTIS.PORTFOLIO_ADDRESSES (ADDRESS, PORTFOLIO) 
	VALUES ('München, Marienplatz', 8);
INSERT INTO NWTIS.PORTFOLIO_ADDRESSES (ADDRESS, PORTFOLIO) 
	VALUES ('Wien, Stephansplatz 7', 8);
INSERT INTO NWTIS.PORTFOLIO_ADDRESSES (ADDRESS, PORTFOLIO) 
	VALUES ('Ivanić-Grad, Croatia', 20);
INSERT INTO NWTIS.PORTFOLIO_ADDRESSES (ADDRESS, PORTFOLIO) 
	VALUES ('Sisak, Croatia', 20);
	
INSERT INTO NWTIS.USERS (FIRSTNAME, LASTNAME, USERNAME, PASSWORD) 
	VALUES ('Krunoslav', 'DomiÄ', 'kdomic', '123456');
INSERT INTO NWTIS.USERS (FIRSTNAME, LASTNAME, USERNAME, PASSWORD) 
	VALUES ('Pero', 'PeriÄ', 'pperic', '123456');
INSERT INTO NWTIS.USERS (FIRSTNAME, LASTNAME, USERNAME, PASSWORD) 
	VALUES ('Administrator', 'Admin', 'admin', '123456');
INSERT INTO NWTIS.USERS (FIRSTNAME, LASTNAME, USERNAME, PASSWORD) 
	VALUES ('Pero2', 'Pero2', 'pperic2', 'pperic2');

	